### ISSUE TITLE
Feat/GA : GA 기능 추가

### ISSUE THREAD

**Issue by cutthebutter** [DeveloperAcademy-POSTECH/MacC-Team7-FallWin#32]
# Issues
GA의 기능을 추가합니다

# To-do

- [x] GA 환경세팅 : 패키지 디펜던시
- [x] 뷰와 액션 트랙킹 포인트 만들기
- [x] 각 부분에 라벨링 추가하기
